Handle last remote stream ID in cow_http2_machine
ninenines/cowlib pull request #109
Opened 2020-11-10 14:33 UTC by zuiderkwast

New function `set_last_streamid/1` sets the last accepted stream ID
to the last known remote stream ID. Frames with a remote stream ID
greater than this are thereafter ignored by `frame/2`, which returns
`{ok, Http2Machine}` for such frames.

2020-11-10 15:15 UTC, zuiderkwast commented
I have tested this locally against a modified version of the Graceful Shutdown branch.

2020-11-10 15:21 UTC, essen commented
You need to ignore (at least some) frames after all the checks, not before. For example if you ignore HEADERS where you currently do, it will not update the HPACK state, and as a result if trailers come in for a legitimate stream the state will not be valid.

2020-11-11 09:55 UTC, zuiderkwast commented
Of course. :facepalm: I assumed HPACK and flow control was done in some earlier stage (e.g. while parsing), but of course it's in the machine. I've updated now. Ignored DATA frames are counted towards the connection flow-control window. Frames that affect the HPACK state are processed and then the result is discarded afterwards.

2020-11-18 11:02 UTC, zuiderkwast commented
Bump.

I updated this a week ago. Do you have time to take a look soon?

2020-11-18 11:14 UTC, essen commented
After Gun 2.0.0-rc.1.

2020-11-20 13:26 UTC, essen requested changes
In general I don't think we need to modify the `*_frame` functions. The PR should act on the returned value from `frame/2` only. I think we should just wrap the result and, depending on the frame, transform the returned tuple into a plain `{ok, State}`. Errors should be returned regardless. Not sure about `send`.

2020-11-20 13:26 UTC, essen commented on src/cow_http2_machine.erl
> +data_frame({data, StreamID, _, Data},
You're doing this before and skipping additional checks. Any reason why?

2020-11-20 13:26 UTC, essen commented on src/cow_http2_machine.erl
> +		client -> client_headers_frame(Frame, State0)
These changes seem unneeded.

2020-11-20 13:26 UTC, essen commented on src/cow_http2_machine.erl
> +	{ok, State};
You don't seem to do the HPACK decode here.

2020-11-20 13:55 UTC, zuiderkwast commented on src/cow_http2_machine.erl
> +data_frame({data, StreamID, _, Data},
Yes, the reason I moved this clause first is that the connection flow control window should be counted regardless of whether StreamID > LastRemoteStreamID.

2020-11-20 13:55 UTC, zuiderkwast commented on src/cow_http2_machine.erl
> +		client -> client_headers_frame(Frame, State0)
That's right, I'll revert these. (I had other changes here before I settled.)

2020-11-20 14:03 UTC, zuiderkwast commented on src/cow_http2_machine.erl
> +	{ok, State};
Oops, yes, I'll revert it. This clause isn't needed. I added this before I realized that `maybe_discard_result` can be used on the results of push_promis_frame/2.

2020-11-20 14:43 UTC, zuiderkwast commented
> In general I don't think we need to modify the `*_frame` functions. The PR should act on the returned value from `frame/2` only. I think we should just wrap the result and, depending on the frame, transform the returned tuple into a plain `{ok, State}`. Errors should be returned regardless.

So, I'll apply `maybe_discard_result/1` on the result regardless of frame type?

Then `maybe_discard_result/1` would need some more logic and cannot simply assume that the 2nd element of the 2nd element is the stream ID. If it's done only for some frame types (as in the current commit plus a few more), `maybe_discard_result/1` function can still have this assumption.

So I think you're right that `data_frame/2`, `rst_stream_frame/2` and `window_update_frame/2` (the one with a stream ID) don't need any changes as long as the result is discarded afterwards.

> Not sure about `send`.

Send can be triggered by `window_update_frame/2`, but I don't think there can ever be any buffered data to send for streams which are ignored in this way, so I think we don't need to add any logic for send results.

2020-11-20 15:07 UTC, zuiderkwast commented on src/cow_http2_machine.erl
> +	{ok, State};
Removed this clause. It's handled by maybe_discard_result/1.

2020-11-20 15:08 UTC, zuiderkwast commented on src/cow_http2_machine.erl
> +data_frame({data, StreamID, _, Data},
Reverted. Also removed the added clause, in favour of maybe_discard_result/1.

2020-11-20 16:33 UTC, essen commented
OK that looks better I'll do a double check this coming week. Thanks!

2020-11-23 08:30 UTC, essen commented
Please update https://github.com/ninenines/cowboy/pull/1471 as well so I can test that it all works as intended.

2020-11-23 10:30 UTC, essen approved these changes

2020-11-27 14:39 UTC, essen commented
Merged, thanks!

2020-11-27 14:39 UTC, closed without merging